apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  name: ex-aao
  application: ex-aao-app
spec:
  adminPassword: admin
  deploymentPlan:
    size: 1
    persistenceEnabled: false
    requireLogin: false
    messageMigration: false
    managementRBACEnabled: true
    journalType: nio
    jolokiaAgentEnabled: false
    image: registry.redhat.io/amq7/amq-broker:7.7
  adminUser: admin
  console:
    expose: true
  acceptors:
    - name: all
      port: 61616
      expose: true